# .github/workflows/publish.yml
name: Publish Simler v4.5.0 to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build tool
        run: python -m pip install --upgrade pip build

      - name: Build the package
        run: python -m build

      - name: Upload artifact (built distributions)
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
    environment:
      name: pypi
      # Optional: uncomment and update with PyPI project URL
      # url: https://pypi.org/project/simler/${{ github.event.release.name }}

    steps:
      - name: Download built distributions
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
        env:
          PYPI_USERNAME: __token__          # fixed value for token auth
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}  # your GitHub secret
