name: Upload Python Package - Simler v4.5.0

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest
    name: Build Simler v4.5.0 Distributions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build release distributions
        run: |
          python -m pip install --upgrade pip build
          python -m build

      - name: Upload distributions artifact
        uses: actions/upload-artifact@v4
        with:
          name: simler-v4.5.0-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/project/simler/4.5.0/

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: simler-v4.5.0-dists
          path: dist/

      - name: Publish Simler v4.5.0 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
